channels:
- conda-forge
dependencies:
- jupyterlab
- git
- pip
- python
- pyiron_base
- pyiron_atomistics
- lammps
- iprpy-data
- pyiron_gui >= 0.0.5
- pyiron_contrib
- pyiron_experimental
- pyiron_gui
- nglview
- seaborn
- pyscal
- jupyterlab
- pyiron-data >=0.0.5
- pymatgen
- voila
- boto3
- botocore
- coscine
- qgrid
- plotly
